# Generated by Django 4.2.3 on 2023-08-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=1000)),
                ('predictor', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=300)),
                ('targetPrice', models.FloatField()),
                ('accuracy', models.FloatField()),
            ],
        ),
    ]
