# Generated by Django 4.2.3 on 2023-09-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromAirport', models.CharField(max_length=3)),
                ('toAirport', models.CharField(max_length=3)),
                ('date', models.CharField(max_length=10)),
                ('airline', models.CharField(max_length=100)),
                ('departs', models.CharField(max_length=8)),
                ('arrives', models.CharField(max_length=8)),
                ('arriveDateChg', models.IntegerField()),
            ],
        ),
    ]
