# Generated by Django 4.2.3 on 2023-10-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passwordHash',
            field=models.BinaryField(),
        ),
    ]
